### PR TITLE
Refine Painless Playground UI/UX

### PR DESCRIPTION
**Pull request by cjcenizal**
Changes in this PR:

* Convert to 2-panel layout.
* Move Context tab into right panel and break out a separate tab for Parameters.
* Use EuiBottomBar for main controls.
* Move Response into Request flyout.
* Prepopulate the playground with the heart script.
* Send debounced requests as the user types and remove the Test button.
* Show request progress/success/failure indicator in "Output" tab.
* Add "Beta" label.
* Refine Context form help text and form components.
* Add links to docs.

Next steps for subsequent PRs:

- From the API docs it looks like the UI is missing a "query" field for score context.
- Improve description copy of each context type.
- Add a docLinks service.
- Fix the odd visual layout issues with the code editors (large gutters, overlapping lines).
- Prepopulate index-selection field with a list of available indices. At a later stage we can enhance this to be a flyout that lets you preview the mappings of each index to help you select the one you want.
- The parameters field should be a component that lets you add key-value pairs via a list editor. There can be a button that lets you switch back and forth between the KV list mode and JSON editing mode.

image

image

image

image

### CODE REVIEW

**Comment by jloleysens** [comment]
I'm liking this direction @cjcenizal ! I think the vertical split makes this feel more like Console which is a heavily used plugin in dev tools :+1:.

[UPDATE]

What do you think of adding the resizable panels component here?

> Move Response from a tab to a modal, triggered by a "Show full response" button in the Output tab

Do you think the context form could similarly live inside a modal or a flyout?

> Prepopulate the playground with the heart script

1000x yes!

**Comment by kertal** [comment]
I agree with @jloleysens, really nice changes, good to align it with Console, will check it out and play with it later on

**Comment by cjcenizal** [comment]
Thanks @jloleysens and @kertal! Made some more changes. I'd love to hear your thoughts.

> What do you think of adding the resizable panels component here?

I haven't noticed any problems with the layout as-is, but I'm also not a power user so I'm not the best person to judge. Have you noticed an urgent problem that this would address? If not then I think it would be a nice addition but low priority.

> Do you think the context form could similarly live inside a modal or a flyout?

My thought was that having it side-by-side with the input pane is useful because you're creating the context consumed by that input pane. So as a user you might want to refer to one while working on the other, which is easier when they don't cover each other up, like a modal would do. I'm not seeing the benefit that a flyout would have vs the existing tab -- do you have a strong opinion on this?

**Comment by cjcenizal** [comment]
@jloleysens On second thought, the resizable panels will also be individually scrollable, which I think will come in handy when I make the code editors for the document and parameters taller. You'll be able to scroll down to see more of these editors without losing your place in the script, and vice versa.

**Review by kertal — COMMENTED** [review]
This are big steps / improvements!  👍 

A few notes from my side:

* Really like the "BETA" :) do we even need a feature flag for it? We're already flagging it as "not ready but you can try it out". This way more users will try it out, since they don't need to go into our Advanced Settings.

* Really nice UI tweak combining the output header with a OK, Progress, Failure icon

* Great to have docs linked!

* While the autosubmit is comfortable, I think it's better to submit with button/shortcut. Or to provide a autosubmit option, to let the user decide. when you write a longer script you might not want to have it submitted with every few keystrokes. You want to have syntax checking, which will be provided in the future in a different way. 
So maybe the  "Show API request" section bottom right, should have a main 'Test/Execute/Start' button, also the "Reset" functionality could be provided here. Similar like you did it in a recent iteration.

And just a few ideas about future stuff (No this PR). What I first tried when starting this was grouping the input / outputs logically: 

Left side: Input Section, Code/Parameters/Context  
Right side: Output Section, Code output / API Request / API Response 

IMG_4027

But we currently don't have an easy way to create such a layout,  but the future of console that @jloleysens presented is pointing in this direction.

**Comment by jloleysens** [comment]
> Really like the "BETA" :) do we even need a feature flag for it? 

I agree, in this case, with the "Beta" badge we don't need to add a feature flag for this.

> Or to provide a autosubmit option, to let the user decide

I agree that if we wanted to introduce this behaviour this would be the best way to do it. We can save that to localStorage, so that it persists. But I view it as an iteration on the REPL pattern (not default behaviour). I think of this as similar to the `Start Job Now` checkbox we added for rollup jobs at creation i.t.o. visual presentation.

**Additional feedback**

Seeing the screenshots I think the visual hierarchy is a bit off with the bottom bar because it overlaps the navbar on the right. Visually it would feel more specifically associated with the painless playground app if it were "behind" and not extending into the nav bar area to the left.

I think, given that we only have one line of horizontal text in the bottom bar perhaps it can have its padding reduced? At the moment it looks quite bulky. I also prefer the look of the `EUIControlBar` here (as a matter of personal preference), it also comes with space management goodies built in.

**Comment by cjcenizal** [comment]
Thank you @kertal and @jloleysens! Glad you like the progress so far. I think we're in agreement that we can leave out the feature flag.

> While the autosubmit is comfortable, I think it's better to submit with button/shortcut. Or to provide a autosubmit option, to let the user decide. when you write a longer script you might not want to have it submitted with every few keystrokes. You want to have syntax checking, which will be provided in the future in a different way.

@jloleysens @kertal I think I need help seeing things from this perspective. Why would the user not want the script submitted every few keystrokes? I agree, we want/need syntax checking and the live-updating output is a substitute for that. But what problem does it introduce? Why is a submit button better? Happy to Zoom about this to gain some insight!

That's a really interesting layout idea. It made me think of the way tools like Final Cut Pro let you drag tabs between panes so you can customize your layout to fit your preference.

Re the bottom bar, I tried using `EuiControlBar` but it doesn't look like it supports containing popovers. And then the Design team pointed out that we can actually store our help links in the Help icon in the Kibana header:

image

I think if we do this then we can just find another place for the "Show API request" button, and maybe the need for the bottom bar goes away entirely. If we keep the bottom bar, we'll need to figure out a solution for the problem with it overlapping the side nav. I've brought this up with the design team, platform team, and core UI team, and haven't found an owner for this yet. That said, I pushed a commit to make it smaller anyway.

How do we feel about this PR? Can we merge + iterate, or do either of you want to block on any of these items?

**Comment by cjcenizal** [comment]
Looks like there is an EUI issue regarding `EuiBottomBar` and its incompatibility with the side nav: https://github.com/elastic/eui/issues/1877

**Comment by jloleysens** [comment]
@cjcenizal in response to your questions regarding the debounced auto-submit:

> Why would the user not want the script submitted every few keystrokes?

The scenario I have in mind is: I am developing a complicated painless script and the right pane is refreshing with messages like `expected a ")" but instead saw "."` (pseudo error). Given that the error text appears in full to the right of the editor this can feel distracting (where in IDEs the error is a squiggle under the text that displays on hover - so a bit more hidden).

[UPDATE]

One other case I can think of is if we are using a Java util like [Random](https://docs.oracle.com/javase/8/docs/api/java/util/Random.html) in our Painless script that delivers different output on each execution we will want to give users control over submission that is not tied to keystrokes.

> Why is a submit button better?

My suggestion is that a submit button (or submit keyboard shortcut) can be used in combination with the auto-submit, but that you opt-out of auto-submit and can control when submission happens.

> How do we feel about this PR?

Given my suggestion I am happy that this be submitted.

FWIW, I've noticed that the `text` type in `EuiControlBar` does allow for rendering `React.ReactNode` because it renders text (so we could render a button with popover there). I've asked Davey what the intention is behind this API so we probably shouldn't be using it in this way without checking.

**Comment by kertal** [comment]
Got nothing to add to @jloleysens, I'm fine with moving forward to further iterate.

**Comment by cjcenizal** [comment]
Thanks both! I'll merge this and write down outstanding items plus the issues you brought up.

**Comment by cjcenizal** [comment]
Oops actually, I don't have permission to merge. Could you merge this @kertal ?

**Pull request merged**
